name: lint

on:
  push:
    branches:
      - master
    paths:
      - '**.py'
      - '**.ppy'
  pull_request:
    paths:
      - '**.py'
      - '**.ppy'

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        vs-versions:
          - 68
        python-version:
          - '3.12'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install vapoursynth-portable==${{ matrix.vs-versions }}
          for /r %i in (requirements.txt) do pip install -r "%i"
          pip install -r requirements-dev.txt

      - name: Running ruff
        run: ruff check . --include '*.ppy'
